# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('keywords', models.ManyToManyField(to='jarvis.KeyWord')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jarvis.User')),
            ],
            bases=('jarvis.user',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jarvis.User')),
                ('shop_name', models.CharField(max_length=200)),
                ('loction_latitude', models.CharField(max_length=100)),
                ('loction_longitude', models.CharField(max_length=100)),
            ],
            bases=('jarvis.user',),
        ),
    ]
